name: test workflow
on:
    push:
      branches:
        - main
        - 'feature/*'
jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: node version
              run: node --version

            - name: Run tests
              run: |
                echo "Running tests..."
                # هنا ممكن تضيف أوامر لتشغيل الاختبارات بتاعتك